//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUIS_pizzaorder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class credit_card
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public credit_card()
        {
            this.user_order_user_cc = new HashSet<user_order_user_cc>();
            this.users = new HashSet<user>();
        }
    
        public int cc_id { get; set; }
        public string name { get; set; }
        public string number { get; set; }
        public Nullable<System.DateTime> expiration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_order_user_cc> user_order_user_cc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
    }
}
