//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUIS_pizzaorder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pizza
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pizza()
        {
            this.users = new HashSet<user>();
        }
    
        public int pizza_id { get; set; }
        public string size { get; set; }
        public string topping_1 { get; set; }
        public string topping_2 { get; set; }
        public string topping_3 { get; set; }
        public string topping_4 { get; set; }
    
        public virtual size size1 { get; set; }
        public virtual topping topping { get; set; }
        public virtual topping topping1 { get; set; }
        public virtual topping topping2 { get; set; }
        public virtual topping topping3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
    }
}
