//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUIS_pizzaorder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_order
    {
        public int user_id { get; set; }
        public int pizza_id { get; set; }
        public decimal total { get; set; }
    
        public virtual user user { get; set; }
    }
}
